refactor(script): rewrite xmde-mpd-notify in perl
Rewrite the MPD notifier in perl instead of bash. This reduces the
number of spawned processes and makes possible to kill the
`mpc idleloop` process easily.

diff --git a/scripts/xmde-mpd-notify b/scripts/xmde-mpd-notify
--- a/scripts/xmde-mpd-notify
+++ b/scripts/xmde-mpd-notify
@@ -1,162 +1,241 @@
-#!/bin/bash
+#!/usr/bin/perl -l
 #
 #   Listen on mpd to detect music changes or play and display a notification.
-#   The listening and fetching of song information is done with mpd.
+#   The listening and fetching of song information is done with mpc.
 #   This script expect to find the song cover picture and the song file under
 #   the same directory. It peeks the first JPEG or PNG file it sees in this
 #   directory.
 #
 
-set -e
+use strict;
+use warnings;
 
-if ! command -v mpc > '/dev/null' 2> '/dev/null' ; then
-    echo "cannot find mpc command"
-    exit 1
-fi >&2
-
-if ! command -v notify-send > '/dev/null' 2> '/dev/null' ; then
-    echo "cannot find notify-send command"
-    exit 1
-fi >&2
-
-if ! command -v perl > '/dev/null' 2> '/dev/null' ; then
-    echo "cannot find perl command"
-    exit 1
-fi >&2
+use File::Temp qw(:POSIX);
+use File::Which;
+use POSIX qw(:sys_wait_h);
 
 
-get_status() {
-    mpc | perl -wnle 's/^\[([^\]]+)\].*$/$1/ and print'
+my %KILL_LIST;
+
+
+sub findConfigDirectoryMpd
+{
+    my ($cpath, $mpdconf, $fh, $line, $ret);
+
+    $cpath = $ENV{'XDG_CONFIG_HOME'};
+    if (!defined($cpath) || ($cpath eq '')) {
+	$cpath = $ENV{'HOME'} . '/.config';
+    }
+
+    if (-f ($cpath . '/mpd/mpd.conf')) {
+	$mpdconf = $cpath . '/mpd/mpd.conf';
+    } elsif (-f ($ENV{'HOME'} . '/.mpdconf')) {
+	$mpdconf = $ENV{'HOME'} . '/.mpdconf';
+    } elsif (-f '/etc/mpd.conf') {
+	$mpdconf = '/etc/mpf.conf';
+    } else {
+	return undef;
+    }
+
+    if (!open($fh, '<', $mpdconf)) {
+	return undef;
+    }
+
+    while (defined($line = <$fh>)) {
+	chomp($line);
+
+	if ($line =~ /^\s*music_directory\s+(["']?.*\S['"]?)\s*$/) {
+	    $ret = $1;
+	    last;
+	}
+    }
+
+    close($fh);
+
+    if (!defined($ret)) {
+	return undef;
+    }
+
+    $ret =~ s/^['"]//;
+    $ret =~ s/['"]$//;
+
+    if ($ret =~ /^~(.*)$/) {
+	$ret = $ENV{HOME} . $1;
+    }
+
+    return $ret;
 }
 
-notify_played_song() {
-    local file="$(mpc current --format='[%file%]')"
-    local title="$(mpc current --format='[%title%]')"
-    local artist="$(mpc current --format='[%artist%]')"
-    local album="$(mpc current --format='[%album%]')"
-    local cover msg sep cmd link
+sub findMusicDirectoryXdg {
+    my ($ret);
 
-    cmd="notify-send -a 'xmde-mpd-notify'"
-    msg=
-    sep=
+    if (defined(which('xdg-user-dirs'))) {
+	$ret = `xdg-user-dirs 'MUSIC'`;
+	chomp($ret);
+	return $ret;
+    }
 
-    if [ "x$file" != 'x' ] ; then
-	cover="$(ls "${MUSIC_DIRECTORY}/${file%/*}"         \
-               | perl -wnle '/\.(jpg|jpeg|png)$/ and print' \
-               | head -n 1)"
-
-	if [ "x$cover" != 'x' ] ; then
-	    cover="${MUSIC_DIRECTORY}/${file%/*}/$cover"
-
-	    if ! echo "$cover" | perl -wnle '/,/ and exit 1' ; then
-		link="$(mktemp --dry-run --tmpdir 'icon.XXXXXX')"
-		ln -s "$cover" "$link"
-		cover="$link"
-	    fi
-
-	    cmd="$cmd -i '$cover'"
-	fi
-    fi
-
-    if [ "x$title" = 'x' ] ; then
-	cmd="$cmd '(Unknown Song)'"
-    else
-	cmd="$cmd '$title'"
-    fi
-
-    if [ "x$artist" != 'x' ] ; then
-	msg="$artist"
-	sep=" - "
-    fi
-
-    if [ "x$album" != 'x' ] ; then
-	msg="$msg$sep$album"
-    fi
-
-    if [ "x$msg" != 'x' ] ; then
-	cmd="$cmd '$msg'"
-    fi
-
-    eval $cmd
-
-    if [ "x$link" != 'x' ] ; then
-	rm "$link"
-    fi
+    return undef;
 }
 
+sub findMusicDirectory {
+    my ($ret);
 
-find_config_directory_mpd() {
-    local cpath mpdconf ret
+    $ret = findConfigDirectoryMpd();
+    if (defined($ret)) {
+	return $ret;
+    }
 
-    if [ "x$XDG_CONFIG_HOME" != 'x' ] ; then
-	cpath="$XDG_CONFIG_HOME"
-    else
-	cpath="$HOME/.config"
-    fi
+    $ret = findMusicDirectoryXdg();
+    if (defined($ret)) {
+	return $ret;
+    }
 
-    if [ -f "$cpath/mpd/mpd.conf" ] ; then
-	mpdconf="$cpath/mpd/mpd.conf"
-    elif [ -f "$HOME/.mpdconf" ] ; then
-	mpdconf="$HOME/.mpdconf"
-    elif [ -f '/etc/mpd.conf' ] ; then
-	mpdconf='/etc/mpf.conf'
-    else
-	return 1
-    fi
-
-    ret="$(perl -wnle '
-        s/^\s*music_directory\s+["'"'"']?(.*\S["'"'"']?)\s*$/$1/ and print
-    ' "$mpdconf")"
-
-    if [ "x$ret" != 'x' ] ; then
-	echo "$ret" | perl -wple '
-            s/^["'"'"']//;
-            s/["'"'"']$//;
-            s:^~:'"$HOME"':;
-        '
-	return 0
-    else
-	return 1
-    fi
+    return undef;
 }
 
-find_music_directory_xdg() {
-    local ret=''
+sub status()
+{
+    my ($line);
 
-    if command -v 'xdg-user-dirs' > '/dev/null' 2> '/dev/null' ; then
-	ret="$(xdg-user-dirs 'MUSIC')"
-    fi
+    foreach $line (split("\n", `mpc status`)) {
+	if ($line =~ m|^\[([^\]]+)\]|) {
+	    return $1;
+	}
+    }
 
-    if [ "x$ret" != 'x' ] ; then
-	echo "$ret"
-	return 0
-    else
-	return 1
-    fi
+    return undef;
 }
 
-find_music_directory() {
-    find_config_directory_mpd || find_music_directory_xdg
+sub notify
+{
+    my ($mdir) = @_;
+    my ($cur, $file, $title, $artist, $album, @cmd);
+    my ($dir, $dh, @imgs, $cover, $covlnk, $msg, $sep);
+
+    $cur = `mpc current --format='[%file%]\n[%title%]\n[%artist%]\n[%album%]'`;
+    chomp($cur);
+
+    @cmd = ('notify-send', '-a', 'xmde-mpd-notify');
+    ($file, $title, $artist, $album) = split("\n", $cur);
+
+    if ($file ne '') {
+	$dir = $file;
+	$dir =~ s|/[^/]*$||;
+
+	if (opendir($dh, $mdir . '/' . $dir)) {
+	    @imgs = grep { m/\.(jpe?g|png)$/ } readdir($dh);
+	    closedir($dh);
+	}
+
+	if (scalar(@imgs) >= 1) {
+	    $cover = $mdir . '/' . $dir . '/' . $imgs[0];
+	}
+
+	if (defined($cover) && ($cover =~ m|,|)) {
+	    $covlnk = tmpnam();
+	    symlink($cover, $covlnk);
+	    $cover = $covlnk;
+	}
+
+	if (defined($cover)) {
+	    push(@cmd, '-i', $cover);
+	}
+    }
+
+    if ($title eq '') {
+	push(@cmd, '(Unknown Song)');
+    } else {
+	push(@cmd, $title);
+    }
+
+    $msg = '';
+    $sep = '';
+
+    if ($artist ne '') {
+	$msg = $artist;
+	$sep = ' - ';
+    }
+
+    if ($album ne '') {
+	$msg .= $sep . $album;
+    }
+
+    if ($msg ne '') {
+	push(@cmd, $msg);
+    }
+
+    system(@cmd);
+
+    if (defined($covlnk)) {
+	unlink($covlnk);
+    }
 }
 
+sub react
+{
+    my ($pid, $fh, $line, $mdir);
 
-MUSIC_DIRECTORY="$(find_music_directory)"
+    if (!which('mpc')) {
+	return;
+    }
 
+    $mdir = findMusicDirectory();
+    if (!defined($mdir)) {
+	printf(STDERR "%s: cannot find mpd music directory\n", $0);
+	return;
+    }
 
-if [ "x$MUSIC_DIRECTORY" = 'x' ] ; then
-    echo "cannot find music directory"
-    exit 1
-fi >&2
+  restart:
+    $pid = open($fh, '-|');
+    if ($pid == 0) {
+	exec ('mpc', 'idleloop');
+	die ($!)
+    }
 
+    $KILL_LIST{$pid} = 1;
 
-trap 'kill $(jobs -p)' 'EXIT'
+    while (1) {
+	if (!defined($line = <$fh>)) {
+	    if (waitpid($pid, WNOHANG) == $pid) {
+		delete($KILL_LIST{$pid});
+		sleep(1);
+		goto restart;
+	    } else {
+		next;
+	    }
+	}
 
-mpc idleloop | while read event ; do
-    status="$(get_status)"
+	chomp($line);
+	if (!($line =~ /player/)) {
+	    next;
+	}
 
-    if [ "x$status" != 'xplaying' ] ; then
-	continue
-    fi
+	if (status() eq 'playing') {
+	    notify($mdir);
+	}
+    }
+}
 
-    notify_played_song
-done
+sub killList
+{
+    my ($pid);
+
+    foreach $pid (keys(%KILL_LIST)) {
+	kill('INT', $pid);
+    }
+
+    exit (0);
+}
+
+sub main
+{
+    $SIG{'INT'} = \&killList;
+    $SIG{'QUIT'} = \&killList;
+    $SIG{'TERM'} = \&killList;
+
+    react();
+}
+
+exit (main(@ARGV));
+__END__
